/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdUser
 */
export interface AdUser {
    /**
     * 
     * @type {string}
     * @memberof AdUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdUser
     */
    intendeduse: string;
}

/**
 * Check if a given object implements the AdUser interface.
 */
export function instanceOfAdUser(value: object): value is AdUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('intendeduse' in value) || value['intendeduse'] === undefined) return false;
    return true;
}

export function AdUserFromJSON(json: any): AdUser {
    return AdUserFromJSONTyped(json, false);
}

export function AdUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'intendeduse': json['intendeduse'],
    };
}

  export function AdUserToJSON(json: any): AdUser {
      return AdUserToJSONTyped(json, false);
  }

  export function AdUserToJSONTyped(value?: AdUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'intendeduse': value['intendeduse'],
    };
}

