/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLog
 */
export interface ApiLog {
    /**
     * 
     * @type {number}
     * @memberof ApiLog
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof ApiLog
     */
    month: number;
    /**
     * 
     * @type {string}
     * @memberof ApiLog
     */
    intendeduse: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLog
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLog
     */
    datasets: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLog
     */
    searchParam: string;
    /**
     * 
     * @type {number}
     * @memberof ApiLog
     */
    count: number;
}

/**
 * Check if a given object implements the ApiLog interface.
 */
export function instanceOfApiLog(value: object): value is ApiLog {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('intendeduse' in value) || value['intendeduse'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('datasets' in value) || value['datasets'] === undefined) return false;
    if (!('searchParam' in value) || value['searchParam'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ApiLogFromJSON(json: any): ApiLog {
    return ApiLogFromJSONTyped(json, false);
}

export function ApiLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLog {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'month': json['month'],
        'intendeduse': json['intendeduse'],
        'path': json['path'],
        'datasets': json['datasets'],
        'searchParam': json['searchParam'],
        'count': json['count'],
    };
}

  export function ApiLogToJSON(json: any): ApiLog {
      return ApiLogToJSONTyped(json, false);
  }

  export function ApiLogToJSONTyped(value?: ApiLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'month': value['month'],
        'intendeduse': value['intendeduse'],
        'path': value['path'],
        'datasets': value['datasets'],
        'searchParam': value['searchParam'],
        'count': value['count'],
    };
}

