/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DatasetStatus = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type DatasetStatus = typeof DatasetStatus[keyof typeof DatasetStatus];


export function instanceOfDatasetStatus(value: any): boolean {
    for (const key in DatasetStatus) {
        if (Object.prototype.hasOwnProperty.call(DatasetStatus, key)) {
            if (DatasetStatus[key as keyof typeof DatasetStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DatasetStatusFromJSON(json: any): DatasetStatus {
    return DatasetStatusFromJSONTyped(json, false);
}

export function DatasetStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetStatus {
    return json as DatasetStatus;
}

export function DatasetStatusToJSON(value?: DatasetStatus | null): any {
    return value as any;
}

export function DatasetStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DatasetStatus {
    return value as DatasetStatus;
}

