/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DatasetType = {
    Timeseries: 'timeseries',
    File: 'file'
} as const;
export type DatasetType = typeof DatasetType[keyof typeof DatasetType];


export function instanceOfDatasetType(value: any): boolean {
    for (const key in DatasetType) {
        if (Object.prototype.hasOwnProperty.call(DatasetType, key)) {
            if (DatasetType[key as keyof typeof DatasetType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DatasetTypeFromJSON(json: any): DatasetType {
    return DatasetTypeFromJSONTyped(json, false);
}

export function DatasetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetType {
    return json as DatasetType;
}

export function DatasetTypeToJSON(value?: DatasetType | null): any {
    return value as any;
}

export function DatasetTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DatasetType {
    return value as DatasetType;
}

