/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DatasetFormat = {
    Csv: 'csv',
    Json: 'json',
    App: 'app',
    _7zip: '7zip',
    Zip: 'zip',
    Xlsx: 'xlsx',
    Xml: 'xml'
} as const;
export type DatasetFormat = typeof DatasetFormat[keyof typeof DatasetFormat];


export function instanceOfDatasetFormat(value: any): boolean {
    for (const key in DatasetFormat) {
        if (Object.prototype.hasOwnProperty.call(DatasetFormat, key)) {
            if (DatasetFormat[key as keyof typeof DatasetFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DatasetFormatFromJSON(json: any): DatasetFormat {
    return DatasetFormatFromJSONTyped(json, false);
}

export function DatasetFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetFormat {
    return json as DatasetFormat;
}

export function DatasetFormatToJSON(value?: DatasetFormat | null): any {
    return value as any;
}

export function DatasetFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): DatasetFormat {
    return value as DatasetFormat;
}

