/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldErrorsValue
 */
export interface FieldErrorsValue {
    /**
     * 
     * @type {any}
     * @memberof FieldErrorsValue
     */
    value?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FieldErrorsValue
     */
    message: string;
}

/**
 * Check if a given object implements the FieldErrorsValue interface.
 */
export function instanceOfFieldErrorsValue(value: object): value is FieldErrorsValue {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function FieldErrorsValueFromJSON(json: any): FieldErrorsValue {
    return FieldErrorsValueFromJSONTyped(json, false);
}

export function FieldErrorsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldErrorsValue {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'message': json['message'],
    };
}

  export function FieldErrorsValueToJSON(json: any): FieldErrorsValue {
      return FieldErrorsValueToJSONTyped(json, false);
  }

  export function FieldErrorsValueToJSONTyped(value?: FieldErrorsValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'message': value['message'],
    };
}

