/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileData
 */
export interface FileData {
    /**
     * 
     * @type {number}
     * @memberof FileData
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof FileData
     */
    modifiedAtUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileData
     */
    createdAtUtc?: Date;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    filenameFi: string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    filenameEn: string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    messageFi: string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    messageEn: string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    fileType: string;
    /**
     * 
     * @type {number}
     * @memberof FileData
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof FileData
     */
    dataFrom: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileData
     */
    dataTo: Date;
    /**
     * 
     * @type {number}
     * @memberof FileData
     */
    datasetId: number;
}

/**
 * Check if a given object implements the FileData interface.
 */
export function instanceOfFileData(value: object): value is FileData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('filenameFi' in value) || value['filenameFi'] === undefined) return false;
    if (!('filenameEn' in value) || value['filenameEn'] === undefined) return false;
    if (!('messageFi' in value) || value['messageFi'] === undefined) return false;
    if (!('messageEn' in value) || value['messageEn'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('dataFrom' in value) || value['dataFrom'] === undefined) return false;
    if (!('dataTo' in value) || value['dataTo'] === undefined) return false;
    if (!('datasetId' in value) || value['datasetId'] === undefined) return false;
    return true;
}

export function FileDataFromJSON(json: any): FileData {
    return FileDataFromJSONTyped(json, false);
}

export function FileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'modifiedAtUtc': json['modifiedAtUtc'] == null ? undefined : (new Date(json['modifiedAtUtc'])),
        'createdAtUtc': json['createdAtUtc'] == null ? undefined : (new Date(json['createdAtUtc'])),
        'filenameFi': json['filenameFi'],
        'filenameEn': json['filenameEn'],
        'messageFi': json['messageFi'],
        'messageEn': json['messageEn'],
        'link': json['link'],
        'fileType': json['fileType'],
        'size': json['size'],
        'dataFrom': (new Date(json['dataFrom'])),
        'dataTo': (new Date(json['dataTo'])),
        'datasetId': json['datasetId'],
    };
}

  export function FileDataToJSON(json: any): FileData {
      return FileDataToJSONTyped(json, false);
  }

  export function FileDataToJSONTyped(value?: FileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'modifiedAtUtc': value['modifiedAtUtc'] == null ? undefined : ((value['modifiedAtUtc']).toISOString()),
        'createdAtUtc': value['createdAtUtc'] == null ? undefined : ((value['createdAtUtc']).toISOString()),
        'filenameFi': value['filenameFi'],
        'filenameEn': value['filenameEn'],
        'messageFi': value['messageFi'],
        'messageEn': value['messageEn'],
        'link': value['link'],
        'fileType': value['fileType'],
        'size': value['size'],
        'dataFrom': ((value['dataFrom']).toISOString()),
        'dataTo': ((value['dataTo']).toISOString()),
        'datasetId': value['datasetId'],
    };
}

