/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDataset404Response
 */
export interface GetDataset404Response {
    /**
     * 
     * @type {string}
     * @memberof GetDataset404Response
     */
    message: string;
}

/**
 * Check if a given object implements the GetDataset404Response interface.
 */
export function instanceOfGetDataset404Response(value: object): value is GetDataset404Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetDataset404ResponseFromJSON(json: any): GetDataset404Response {
    return GetDataset404ResponseFromJSONTyped(json, false);
}

export function GetDataset404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDataset404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function GetDataset404ResponseToJSON(json: any): GetDataset404Response {
      return GetDataset404ResponseToJSONTyped(json, false);
  }

  export function GetDataset404ResponseToJSONTyped(value?: GetDataset404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

