/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IWithPaginationDatasetSearchResult } from './IWithPaginationDatasetSearchResult';
import {
    IWithPaginationDatasetSearchResultFromJSON,
    IWithPaginationDatasetSearchResultFromJSONTyped,
    IWithPaginationDatasetSearchResultToJSON,
    IWithPaginationDatasetSearchResultToJSONTyped,
} from './IWithPaginationDatasetSearchResult';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { IWithPaginationDatasetShort } from './IWithPaginationDatasetShort';
import {
    IWithPaginationDatasetShortFromJSON,
    IWithPaginationDatasetShortFromJSONTyped,
    IWithPaginationDatasetShortToJSON,
    IWithPaginationDatasetShortToJSONTyped,
} from './IWithPaginationDatasetShort';
import type { PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn } from './PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn';
import {
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnFromJSON,
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnFromJSONTyped,
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnToJSON,
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnToJSONTyped,
} from './PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn';

/**
 * 
 * @export
 * @interface GetDatasetShorts200Response
 */
export interface GetDatasetShorts200Response {
    /**
     * 
     * @type {Array<PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn>}
     * @memberof GetDatasetShorts200Response
     */
    data: Array<PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn>;
    /**
     * 
     * @type {IPagination}
     * @memberof GetDatasetShorts200Response
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the GetDatasetShorts200Response interface.
 */
export function instanceOfGetDatasetShorts200Response(value: object): value is GetDatasetShorts200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function GetDatasetShorts200ResponseFromJSON(json: any): GetDatasetShorts200Response {
    return GetDatasetShorts200ResponseFromJSONTyped(json, false);
}

export function GetDatasetShorts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDatasetShorts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnFromJSON)),
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function GetDatasetShorts200ResponseToJSON(json: any): GetDatasetShorts200Response {
      return GetDatasetShorts200ResponseToJSONTyped(json, false);
  }

  export function GetDatasetShorts200ResponseToJSONTyped(value?: GetDatasetShorts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnToJSON)),
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

