/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusResponse } from './StatusResponse';
import {
    StatusResponseFromJSON,
    StatusResponseFromJSONTyped,
    StatusResponseToJSON,
    StatusResponseToJSONTyped,
} from './StatusResponse';

/**
 * 
 * @export
 * @interface HealthStatus
 */
export interface HealthStatus {
    /**
     * 
     * @type {StatusResponse}
     * @memberof HealthStatus
     */
    network: StatusResponse;
    /**
     * 
     * @type {StatusResponse}
     * @memberof HealthStatus
     */
    database: StatusResponse;
    /**
     * 
     * @type {StatusResponse}
     * @memberof HealthStatus
     */
    app: StatusResponse;
}

/**
 * Check if a given object implements the HealthStatus interface.
 */
export function instanceOfHealthStatus(value: object): value is HealthStatus {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('database' in value) || value['database'] === undefined) return false;
    if (!('app' in value) || value['app'] === undefined) return false;
    return true;
}

export function HealthStatusFromJSON(json: any): HealthStatus {
    return HealthStatusFromJSONTyped(json, false);
}

export function HealthStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'network': StatusResponseFromJSON(json['network']),
        'database': StatusResponseFromJSON(json['database']),
        'app': StatusResponseFromJSON(json['app']),
    };
}

  export function HealthStatusToJSON(json: any): HealthStatus {
      return HealthStatusToJSONTyped(json, false);
  }

  export function HealthStatusToJSONTyped(value?: HealthStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': StatusResponseToJSON(value['network']),
        'database': StatusResponseToJSON(value['database']),
        'app': StatusResponseToJSON(value['app']),
    };
}

