/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { FileData } from './FileData';
import {
    FileDataFromJSON,
    FileDataFromJSONTyped,
    FileDataToJSON,
    FileDataToJSONTyped,
} from './FileData';

/**
 * 
 * @export
 * @interface IWithPaginationFileData
 */
export interface IWithPaginationFileData {
    /**
     * 
     * @type {Array<FileData>}
     * @memberof IWithPaginationFileData
     */
    data: Array<FileData>;
    /**
     * 
     * @type {IPagination}
     * @memberof IWithPaginationFileData
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the IWithPaginationFileData interface.
 */
export function instanceOfIWithPaginationFileData(value: object): value is IWithPaginationFileData {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function IWithPaginationFileDataFromJSON(json: any): IWithPaginationFileData {
    return IWithPaginationFileDataFromJSONTyped(json, false);
}

export function IWithPaginationFileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWithPaginationFileData {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(FileDataFromJSON)),
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function IWithPaginationFileDataToJSON(json: any): IWithPaginationFileData {
      return IWithPaginationFileDataToJSONTyped(json, false);
  }

  export function IWithPaginationFileDataToJSONTyped(value?: IWithPaginationFileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(FileDataToJSON)),
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

