/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeseriesDataOneRowPerTimePeriod } from './TimeseriesDataOneRowPerTimePeriod';
import {
    TimeseriesDataOneRowPerTimePeriodFromJSON,
    TimeseriesDataOneRowPerTimePeriodFromJSONTyped,
    TimeseriesDataOneRowPerTimePeriodToJSON,
    TimeseriesDataOneRowPerTimePeriodToJSONTyped,
} from './TimeseriesDataOneRowPerTimePeriod';
import type { TimeseriesData } from './TimeseriesData';
import {
    TimeseriesDataFromJSON,
    TimeseriesDataFromJSONTyped,
    TimeseriesDataToJSON,
    TimeseriesDataToJSONTyped,
} from './TimeseriesData';

/**
 * 
 * @export
 * @interface IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
 */
export interface IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner {
    /**
     * 
     * @type {number}
     * @memberof IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
     */
    datasetId: number;
    /**
     * 
     * @type {Date}
     * @memberof IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
     */
    modifiedAtUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
     */
    value: number;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: string; }}
     * @memberof IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner
     */
    additionalJson?: { [key: string]: string; };
}

/**
 * Check if a given object implements the IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner interface.
 */
export function instanceOfIWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner(value: object): value is IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner {
    if (!('datasetId' in value) || value['datasetId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerFromJSON(json: any): IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner {
    return IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerFromJSONTyped(json, false);
}

export function IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'datasetId': json['datasetId'],
        'modifiedAtUtc': json['modifiedAtUtc'] == null ? undefined : (new Date(json['modifiedAtUtc'])),
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'value': json['value'],
        'additionalJson': json['additionalJson'] == null ? undefined : json['additionalJson'],
    };
}

  export function IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerToJSON(json: any): IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner {
      return IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerToJSONTyped(json, false);
  }

  export function IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerToJSONTyped(value?: IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datasetId': value['datasetId'],
        'modifiedAtUtc': value['modifiedAtUtc'] == null ? undefined : ((value['modifiedAtUtc']).toISOString()),
        'startTime': ((value['startTime']).toISOString()),
        'endTime': ((value['endTime']).toISOString()),
        'value': value['value'],
        'additionalJson': value['additionalJson'],
    };
}

