/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { DatasetSearchResult } from './DatasetSearchResult';
import {
    DatasetSearchResultFromJSON,
    DatasetSearchResultFromJSONTyped,
    DatasetSearchResultToJSON,
    DatasetSearchResultToJSONTyped,
} from './DatasetSearchResult';

/**
 * 
 * @export
 * @interface IWithPaginationDatasetSearchResult
 */
export interface IWithPaginationDatasetSearchResult {
    /**
     * 
     * @type {Array<DatasetSearchResult>}
     * @memberof IWithPaginationDatasetSearchResult
     */
    data: Array<DatasetSearchResult>;
    /**
     * 
     * @type {IPagination}
     * @memberof IWithPaginationDatasetSearchResult
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the IWithPaginationDatasetSearchResult interface.
 */
export function instanceOfIWithPaginationDatasetSearchResult(value: object): value is IWithPaginationDatasetSearchResult {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function IWithPaginationDatasetSearchResultFromJSON(json: any): IWithPaginationDatasetSearchResult {
    return IWithPaginationDatasetSearchResultFromJSONTyped(json, false);
}

export function IWithPaginationDatasetSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWithPaginationDatasetSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DatasetSearchResultFromJSON)),
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function IWithPaginationDatasetSearchResultToJSON(json: any): IWithPaginationDatasetSearchResult {
      return IWithPaginationDatasetSearchResultToJSONTyped(json, false);
  }

  export function IWithPaginationDatasetSearchResultToJSONTyped(value?: IWithPaginationDatasetSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(DatasetSearchResultToJSON)),
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

