/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { TimeseriesData } from './TimeseriesData';
import {
    TimeseriesDataFromJSON,
    TimeseriesDataFromJSONTyped,
    TimeseriesDataToJSON,
    TimeseriesDataToJSONTyped,
} from './TimeseriesData';

/**
 * 
 * @export
 * @interface IWithPaginationTimeseriesData
 */
export interface IWithPaginationTimeseriesData {
    /**
     * 
     * @type {Array<TimeseriesData>}
     * @memberof IWithPaginationTimeseriesData
     */
    data: Array<TimeseriesData>;
    /**
     * 
     * @type {IPagination}
     * @memberof IWithPaginationTimeseriesData
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the IWithPaginationTimeseriesData interface.
 */
export function instanceOfIWithPaginationTimeseriesData(value: object): value is IWithPaginationTimeseriesData {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function IWithPaginationTimeseriesDataFromJSON(json: any): IWithPaginationTimeseriesData {
    return IWithPaginationTimeseriesDataFromJSONTyped(json, false);
}

export function IWithPaginationTimeseriesDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWithPaginationTimeseriesData {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TimeseriesDataFromJSON)),
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function IWithPaginationTimeseriesDataToJSON(json: any): IWithPaginationTimeseriesData {
      return IWithPaginationTimeseriesDataToJSONTyped(json, false);
  }

  export function IWithPaginationTimeseriesDataToJSONTyped(value?: IWithPaginationTimeseriesData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TimeseriesDataToJSON)),
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

