/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn } from './PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn';
import {
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnFromJSON,
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnFromJSONTyped,
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnToJSON,
    PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnToJSONTyped,
} from './PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn';

/**
 * 
 * @export
 * @interface IWithPaginationDatasetShort
 */
export interface IWithPaginationDatasetShort {
    /**
     * 
     * @type {Array<PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn>}
     * @memberof IWithPaginationDatasetShort
     */
    data: Array<PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEn>;
    /**
     * 
     * @type {IPagination}
     * @memberof IWithPaginationDatasetShort
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the IWithPaginationDatasetShort interface.
 */
export function instanceOfIWithPaginationDatasetShort(value: object): value is IWithPaginationDatasetShort {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function IWithPaginationDatasetShortFromJSON(json: any): IWithPaginationDatasetShort {
    return IWithPaginationDatasetShortFromJSONTyped(json, false);
}

export function IWithPaginationDatasetShortFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWithPaginationDatasetShort {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnFromJSON)),
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function IWithPaginationDatasetShortToJSON(json: any): IWithPaginationDatasetShort {
      return IWithPaginationDatasetShortToJSONTyped(json, false);
  }

  export function IWithPaginationDatasetShortToJSONTyped(value?: IWithPaginationDatasetShort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PickDatasetIdOrModifiedAtUtcOrTypeOrOrganizationOrNameFiOrNameEnOrDescriptionFiOrDescriptionEnOrContentGroupsFiOrContentGroupsEnOrKeyWordsFiOrKeyWordsEnOrAvailableFormatsOrDataPeriodFiOrDataPeriodEnOrUnitFiOrUnitEnToJSON)),
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

