/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface IWithPaginationNotificationArray
 */
export interface IWithPaginationNotificationArray {
    /**
     * 
     * @type {Array<Array<Notification>>}
     * @memberof IWithPaginationNotificationArray
     */
    data: Array<Array<Notification>>;
    /**
     * 
     * @type {IPagination}
     * @memberof IWithPaginationNotificationArray
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the IWithPaginationNotificationArray interface.
 */
export function instanceOfIWithPaginationNotificationArray(value: object): value is IWithPaginationNotificationArray {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function IWithPaginationNotificationArrayFromJSON(json: any): IWithPaginationNotificationArray {
    return IWithPaginationNotificationArrayFromJSONTyped(json, false);
}

export function IWithPaginationNotificationArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWithPaginationNotificationArray {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function IWithPaginationNotificationArrayToJSON(json: any): IWithPaginationNotificationArray {
      return IWithPaginationNotificationArrayToJSONTyped(json, false);
  }

  export function IWithPaginationNotificationArrayToJSONTyped(value?: IWithPaginationNotificationArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

