/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface License
 */
export interface License {
    /**
     * 
     * @type {string}
     * @memberof License
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof License
     */
    termsLink: string;
}

/**
 * Check if a given object implements the License interface.
 */
export function instanceOfLicense(value: object): value is License {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('termsLink' in value) || value['termsLink'] === undefined) return false;
    return true;
}

export function LicenseFromJSON(json: any): License {
    return LicenseFromJSONTyped(json, false);
}

export function LicenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): License {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'termsLink': json['termsLink'],
    };
}

  export function LicenseToJSON(json: any): License {
      return LicenseToJSONTyped(json, false);
  }

  export function LicenseToJSONTyped(value?: License | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'termsLink': value['termsLink'],
    };
}

