/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonitoringAisErrorResult } from './MonitoringAisErrorResult';
import {
    MonitoringAisErrorResultFromJSON,
    MonitoringAisErrorResultFromJSONTyped,
    MonitoringAisErrorResultToJSON,
    MonitoringAisErrorResultToJSONTyped,
} from './MonitoringAisErrorResult';
import type { MonitoringTimeseriesResult } from './MonitoringTimeseriesResult';
import {
    MonitoringTimeseriesResultFromJSON,
    MonitoringTimeseriesResultFromJSONTyped,
    MonitoringTimeseriesResultToJSON,
    MonitoringTimeseriesResultToJSONTyped,
} from './MonitoringTimeseriesResult';

/**
 * 
 * @export
 * @interface MonitoringResult
 */
export interface MonitoringResult {
    /**
     * 
     * @type {Array<MonitoringAisErrorResult>}
     * @memberof MonitoringResult
     */
    aisErrors: Array<MonitoringAisErrorResult>;
    /**
     * 
     * @type {Array<MonitoringTimeseriesResult>}
     * @memberof MonitoringResult
     */
    timeseries: Array<MonitoringTimeseriesResult>;
}

/**
 * Check if a given object implements the MonitoringResult interface.
 */
export function instanceOfMonitoringResult(value: object): value is MonitoringResult {
    if (!('aisErrors' in value) || value['aisErrors'] === undefined) return false;
    if (!('timeseries' in value) || value['timeseries'] === undefined) return false;
    return true;
}

export function MonitoringResultFromJSON(json: any): MonitoringResult {
    return MonitoringResultFromJSONTyped(json, false);
}

export function MonitoringResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoringResult {
    if (json == null) {
        return json;
    }
    return {
        
        'aisErrors': ((json['aisErrors'] as Array<any>).map(MonitoringAisErrorResultFromJSON)),
        'timeseries': ((json['timeseries'] as Array<any>).map(MonitoringTimeseriesResultFromJSON)),
    };
}

  export function MonitoringResultToJSON(json: any): MonitoringResult {
      return MonitoringResultToJSONTyped(json, false);
  }

  export function MonitoringResultToJSONTyped(value?: MonitoringResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aisErrors': ((value['aisErrors'] as Array<any>).map(MonitoringAisErrorResultToJSON)),
        'timeseries': ((value['timeseries'] as Array<any>).map(MonitoringTimeseriesResultToJSON)),
    };
}

