/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonitoringTimeseriesResult
 */
export interface MonitoringTimeseriesResult {
    /**
     * 
     * @type {boolean}
     * @memberof MonitoringTimeseriesResult
     */
    isMoreThan2CadencesLate?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MonitoringTimeseriesResult
     */
    maxModTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof MonitoringTimeseriesResult
     */
    expectedUpdateCadenceMin?: number;
    /**
     * 
     * @type {string}
     * @memberof MonitoringTimeseriesResult
     */
    updateCadence?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MonitoringTimeseriesResult
     */
    isPublic: boolean;
    /**
     * 
     * @type {number}
     * @memberof MonitoringTimeseriesResult
     */
    numericId: number;
    /**
     * 
     * @type {string}
     * @memberof MonitoringTimeseriesResult
     */
    id: string;
}

/**
 * Check if a given object implements the MonitoringTimeseriesResult interface.
 */
export function instanceOfMonitoringTimeseriesResult(value: object): value is MonitoringTimeseriesResult {
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('numericId' in value) || value['numericId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MonitoringTimeseriesResultFromJSON(json: any): MonitoringTimeseriesResult {
    return MonitoringTimeseriesResultFromJSONTyped(json, false);
}

export function MonitoringTimeseriesResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoringTimeseriesResult {
    if (json == null) {
        return json;
    }
    return {
        
        'isMoreThan2CadencesLate': json['isMoreThan2CadencesLate'] == null ? undefined : json['isMoreThan2CadencesLate'],
        'maxModTime': json['maxModTime'] == null ? undefined : (new Date(json['maxModTime'])),
        'expectedUpdateCadenceMin': json['expectedUpdateCadenceMin'] == null ? undefined : json['expectedUpdateCadenceMin'],
        'updateCadence': json['updateCadence'] == null ? undefined : json['updateCadence'],
        'isPublic': json['isPublic'],
        'numericId': json['numericId'],
        'id': json['id'],
    };
}

  export function MonitoringTimeseriesResultToJSON(json: any): MonitoringTimeseriesResult {
      return MonitoringTimeseriesResultToJSONTyped(json, false);
  }

  export function MonitoringTimeseriesResultToJSONTyped(value?: MonitoringTimeseriesResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isMoreThan2CadencesLate': value['isMoreThan2CadencesLate'],
        'maxModTime': value['maxModTime'] == null ? undefined : ((value['maxModTime']).toISOString()),
        'expectedUpdateCadenceMin': value['expectedUpdateCadenceMin'],
        'updateCadence': value['updateCadence'],
        'isPublic': value['isPublic'],
        'numericId': value['numericId'],
        'id': value['id'],
    };
}

