/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {number}
     * @memberof Notification
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    modifiedAtUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    startTimeUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    endTimeUtc: Date;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    messageFi: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    messageEn: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    linkFi?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    linkEn?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    linkTextFi?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    linkTextEn?: string;
}

/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startTimeUtc' in value) || value['startTimeUtc'] === undefined) return false;
    if (!('endTimeUtc' in value) || value['endTimeUtc'] === undefined) return false;
    if (!('messageFi' in value) || value['messageFi'] === undefined) return false;
    if (!('messageEn' in value) || value['messageEn'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'modifiedAtUtc': json['modifiedAtUtc'] == null ? undefined : (new Date(json['modifiedAtUtc'])),
        'startTimeUtc': (new Date(json['startTimeUtc'])),
        'endTimeUtc': (new Date(json['endTimeUtc'])),
        'messageFi': json['messageFi'],
        'messageEn': json['messageEn'],
        'linkFi': json['linkFi'] == null ? undefined : json['linkFi'],
        'linkEn': json['linkEn'] == null ? undefined : json['linkEn'],
        'linkTextFi': json['linkTextFi'] == null ? undefined : json['linkTextFi'],
        'linkTextEn': json['linkTextEn'] == null ? undefined : json['linkTextEn'],
    };
}

  export function NotificationToJSON(json: any): Notification {
      return NotificationToJSONTyped(json, false);
  }

  export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'modifiedAtUtc': value['modifiedAtUtc'] == null ? undefined : ((value['modifiedAtUtc']).toISOString()),
        'startTimeUtc': ((value['startTimeUtc']).toISOString()),
        'endTimeUtc': ((value['endTimeUtc']).toISOString()),
        'messageFi': value['messageFi'],
        'messageEn': value['messageEn'],
        'linkFi': value['linkFi'],
        'linkEn': value['linkEn'],
        'linkTextFi': value['linkTextFi'],
        'linkTextEn': value['linkTextEn'],
    };
}

