/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface OmitFileDataPrivateId
 */
export interface OmitFileDataPrivateId {
    /**
     * 
     * @type {Date}
     * @memberof OmitFileDataPrivateId
     */
    modifiedAtUtc?: Date;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    datasetId: string;
    /**
     * 
     * @type {Date}
     * @memberof OmitFileDataPrivateId
     */
    createdAtUtc?: Date;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    filenameFi: string;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    filenameEn: string;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    messageFi: string;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    messageEn: string;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof OmitFileDataPrivateId
     */
    fileType: string;
    /**
     * 
     * @type {number}
     * @memberof OmitFileDataPrivateId
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof OmitFileDataPrivateId
     */
    dataFrom: Date;
    /**
     * 
     * @type {Date}
     * @memberof OmitFileDataPrivateId
     */
    dataTo: Date;
}

/**
 * Check if a given object implements the OmitFileDataPrivateId interface.
 */
export function instanceOfOmitFileDataPrivateId(value: object): value is OmitFileDataPrivateId {
    if (!('datasetId' in value) || value['datasetId'] === undefined) return false;
    if (!('filenameFi' in value) || value['filenameFi'] === undefined) return false;
    if (!('filenameEn' in value) || value['filenameEn'] === undefined) return false;
    if (!('messageFi' in value) || value['messageFi'] === undefined) return false;
    if (!('messageEn' in value) || value['messageEn'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('dataFrom' in value) || value['dataFrom'] === undefined) return false;
    if (!('dataTo' in value) || value['dataTo'] === undefined) return false;
    return true;
}

export function OmitFileDataPrivateIdFromJSON(json: any): OmitFileDataPrivateId {
    return OmitFileDataPrivateIdFromJSONTyped(json, false);
}

export function OmitFileDataPrivateIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmitFileDataPrivateId {
    if (json == null) {
        return json;
    }
    return {
        
        'modifiedAtUtc': json['modifiedAtUtc'] == null ? undefined : (new Date(json['modifiedAtUtc'])),
        'datasetId': json['datasetId'],
        'createdAtUtc': json['createdAtUtc'] == null ? undefined : (new Date(json['createdAtUtc'])),
        'filenameFi': json['filenameFi'],
        'filenameEn': json['filenameEn'],
        'messageFi': json['messageFi'],
        'messageEn': json['messageEn'],
        'link': json['link'],
        'fileType': json['fileType'],
        'size': json['size'],
        'dataFrom': (new Date(json['dataFrom'])),
        'dataTo': (new Date(json['dataTo'])),
    };
}

  export function OmitFileDataPrivateIdToJSON(json: any): OmitFileDataPrivateId {
      return OmitFileDataPrivateIdToJSONTyped(json, false);
  }

  export function OmitFileDataPrivateIdToJSONTyped(value?: OmitFileDataPrivateId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modifiedAtUtc': value['modifiedAtUtc'] == null ? undefined : ((value['modifiedAtUtc']).toISOString()),
        'datasetId': value['datasetId'],
        'createdAtUtc': value['createdAtUtc'] == null ? undefined : ((value['createdAtUtc']).toISOString()),
        'filenameFi': value['filenameFi'],
        'filenameEn': value['filenameEn'],
        'messageFi': value['messageFi'],
        'messageEn': value['messageEn'],
        'link': value['link'],
        'fileType': value['fileType'],
        'size': value['size'],
        'dataFrom': ((value['dataFrom']).toISOString()),
        'dataTo': ((value['dataTo']).toISOString()),
    };
}

