/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface OmitNotificationIdOrModifiedAtUtc
 */
export interface OmitNotificationIdOrModifiedAtUtc {
    /**
     * 
     * @type {string}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    messageFi: string;
    /**
     * 
     * @type {string}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    messageEn: string;
    /**
     * 
     * @type {Date}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    startTimeUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    endTimeUtc: Date;
    /**
     * 
     * @type {string}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    linkFi?: string;
    /**
     * 
     * @type {string}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    linkEn?: string;
    /**
     * 
     * @type {string}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    linkTextFi?: string;
    /**
     * 
     * @type {string}
     * @memberof OmitNotificationIdOrModifiedAtUtc
     */
    linkTextEn?: string;
}

/**
 * Check if a given object implements the OmitNotificationIdOrModifiedAtUtc interface.
 */
export function instanceOfOmitNotificationIdOrModifiedAtUtc(value: object): value is OmitNotificationIdOrModifiedAtUtc {
    if (!('messageFi' in value) || value['messageFi'] === undefined) return false;
    if (!('messageEn' in value) || value['messageEn'] === undefined) return false;
    if (!('startTimeUtc' in value) || value['startTimeUtc'] === undefined) return false;
    if (!('endTimeUtc' in value) || value['endTimeUtc'] === undefined) return false;
    return true;
}

export function OmitNotificationIdOrModifiedAtUtcFromJSON(json: any): OmitNotificationIdOrModifiedAtUtc {
    return OmitNotificationIdOrModifiedAtUtcFromJSONTyped(json, false);
}

export function OmitNotificationIdOrModifiedAtUtcFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmitNotificationIdOrModifiedAtUtc {
    if (json == null) {
        return json;
    }
    return {
        
        'messageFi': json['messageFi'],
        'messageEn': json['messageEn'],
        'startTimeUtc': (new Date(json['startTimeUtc'])),
        'endTimeUtc': (new Date(json['endTimeUtc'])),
        'linkFi': json['linkFi'] == null ? undefined : json['linkFi'],
        'linkEn': json['linkEn'] == null ? undefined : json['linkEn'],
        'linkTextFi': json['linkTextFi'] == null ? undefined : json['linkTextFi'],
        'linkTextEn': json['linkTextEn'] == null ? undefined : json['linkTextEn'],
    };
}

  export function OmitNotificationIdOrModifiedAtUtcToJSON(json: any): OmitNotificationIdOrModifiedAtUtc {
      return OmitNotificationIdOrModifiedAtUtcToJSONTyped(json, false);
  }

  export function OmitNotificationIdOrModifiedAtUtcToJSONTyped(value?: OmitNotificationIdOrModifiedAtUtc | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageFi': value['messageFi'],
        'messageEn': value['messageEn'],
        'startTimeUtc': ((value['startTimeUtc']).toISOString()),
        'endTimeUtc': ((value['endTimeUtc']).toISOString()),
        'linkFi': value['linkFi'],
        'linkEn': value['linkEn'],
        'linkTextFi': value['linkTextFi'],
        'linkTextEn': value['linkTextEn'],
    };
}

