/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId
 */
export interface PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId {
    /**
     * 
     * @type {Date}
     * @memberof PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId
     */
    modifiedAtUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId
     */
    value: number;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: string; }}
     * @memberof PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId
     */
    additionalJson?: { [key: string]: string; };
}

/**
 * Check if a given object implements the PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId interface.
 */
export function instanceOfPickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId(value: object): value is PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId {
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrIdFromJSON(json: any): PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId {
    return PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrIdFromJSONTyped(json, false);
}

export function PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId {
    if (json == null) {
        return json;
    }
    return {
        
        'modifiedAtUtc': json['modifiedAtUtc'] == null ? undefined : (new Date(json['modifiedAtUtc'])),
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'value': json['value'],
        'additionalJson': json['additionalJson'] == null ? undefined : json['additionalJson'],
    };
}

  export function PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrIdToJSON(json: any): PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId {
      return PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrIdToJSONTyped(json, false);
  }

  export function PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrIdToJSONTyped(value?: PickTimeseriesDataPrivateExcludeKeyofTimeseriesDataPrivateDatasetIdOrId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modifiedAtUtc': value['modifiedAtUtc'] == null ? undefined : ((value['modifiedAtUtc']).toISOString()),
        'startTime': ((value['startTime']).toISOString()),
        'endTime': ((value['endTime']).toISOString()),
        'value': value['value'],
        'additionalJson': value['additionalJson'],
    };
}

