/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeseriesData
 */
export interface TimeseriesData {
    /**
     * 
     * @type {Date}
     * @memberof TimeseriesData
     */
    modifiedAtUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeseriesData
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeseriesData
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof TimeseriesData
     */
    value: number;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: string; }}
     * @memberof TimeseriesData
     */
    additionalJson?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof TimeseriesData
     */
    datasetId: number;
}

/**
 * Check if a given object implements the TimeseriesData interface.
 */
export function instanceOfTimeseriesData(value: object): value is TimeseriesData {
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('datasetId' in value) || value['datasetId'] === undefined) return false;
    return true;
}

export function TimeseriesDataFromJSON(json: any): TimeseriesData {
    return TimeseriesDataFromJSONTyped(json, false);
}

export function TimeseriesDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesData {
    if (json == null) {
        return json;
    }
    return {
        
        'modifiedAtUtc': json['modifiedAtUtc'] == null ? undefined : (new Date(json['modifiedAtUtc'])),
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'value': json['value'],
        'additionalJson': json['additionalJson'] == null ? undefined : json['additionalJson'],
        'datasetId': json['datasetId'],
    };
}

  export function TimeseriesDataToJSON(json: any): TimeseriesData {
      return TimeseriesDataToJSONTyped(json, false);
  }

  export function TimeseriesDataToJSONTyped(value?: TimeseriesData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modifiedAtUtc': value['modifiedAtUtc'] == null ? undefined : ((value['modifiedAtUtc']).toISOString()),
        'startTime': ((value['startTime']).toISOString()),
        'endTime': ((value['endTime']).toISOString()),
        'value': value['value'],
        'additionalJson': value['additionalJson'],
        'datasetId': value['datasetId'],
    };
}

