/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeseriesDataOneRowPerTimePeriodValue } from './TimeseriesDataOneRowPerTimePeriodValue';
import {
    TimeseriesDataOneRowPerTimePeriodValueFromJSON,
    TimeseriesDataOneRowPerTimePeriodValueFromJSONTyped,
    TimeseriesDataOneRowPerTimePeriodValueToJSON,
    TimeseriesDataOneRowPerTimePeriodValueToJSONTyped,
} from './TimeseriesDataOneRowPerTimePeriodValue';

/**
 * 
 * @export
 * @interface TimeseriesDataOneRowPerTimePeriod
 */
export interface TimeseriesDataOneRowPerTimePeriod {
    [key: string]: TimeseriesDataOneRowPerTimePeriodValue | any;
    /**
     * 
     * @type {Date}
     * @memberof TimeseriesDataOneRowPerTimePeriod
     */
    endTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimeseriesDataOneRowPerTimePeriod
     */
    startTime: Date;
}

/**
 * Check if a given object implements the TimeseriesDataOneRowPerTimePeriod interface.
 */
export function instanceOfTimeseriesDataOneRowPerTimePeriod(value: object): value is TimeseriesDataOneRowPerTimePeriod {
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    return true;
}

export function TimeseriesDataOneRowPerTimePeriodFromJSON(json: any): TimeseriesDataOneRowPerTimePeriod {
    return TimeseriesDataOneRowPerTimePeriodFromJSONTyped(json, false);
}

export function TimeseriesDataOneRowPerTimePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesDataOneRowPerTimePeriod {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'endTime': (new Date(json['endTime'])),
        'startTime': (new Date(json['startTime'])),
    };
}

  export function TimeseriesDataOneRowPerTimePeriodToJSON(json: any): TimeseriesDataOneRowPerTimePeriod {
      return TimeseriesDataOneRowPerTimePeriodToJSONTyped(json, false);
  }

  export function TimeseriesDataOneRowPerTimePeriodToJSONTyped(value?: TimeseriesDataOneRowPerTimePeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'endTime': ((value['endTime']).toISOString()),
        'startTime': ((value['startTime']).toISOString()),
    };
}

