/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod } from './IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod';
import {
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodFromJSON,
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodFromJSONTyped,
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodToJSON,
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodToJSONTyped,
} from './IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriod';
import type { TimeseriesDataCsvResponse } from './TimeseriesDataCsvResponse';
import {
    TimeseriesDataCsvResponseFromJSON,
    TimeseriesDataCsvResponseFromJSONTyped,
    TimeseriesDataCsvResponseToJSON,
    TimeseriesDataCsvResponseToJSONTyped,
} from './TimeseriesDataCsvResponse';

/**
 * 
 * @export
 * @interface TimeseriesDataResponse
 */
export interface TimeseriesDataResponse {
    /**
     * 
     * @type {string}
     * @memberof TimeseriesDataResponse
     */
    data: string;
    /**
     * 
     * @type {IPagination}
     * @memberof TimeseriesDataResponse
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the TimeseriesDataResponse interface.
 */
export function instanceOfTimeseriesDataResponse(value: object): value is TimeseriesDataResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function TimeseriesDataResponseFromJSON(json: any): TimeseriesDataResponse {
    return TimeseriesDataResponseFromJSONTyped(json, false);
}

export function TimeseriesDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function TimeseriesDataResponseToJSON(json: any): TimeseriesDataResponse {
      return TimeseriesDataResponseToJSONTyped(json, false);
  }

  export function TimeseriesDataResponseToJSONTyped(value?: TimeseriesDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

