/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';
import type { IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner } from './IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner';
import {
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerFromJSON,
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerFromJSONTyped,
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerToJSON,
    IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerToJSONTyped,
} from './IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner';

/**
 * 
 * @export
 * @interface TimeseriesDataJsonResponse
 */
export interface TimeseriesDataJsonResponse {
    /**
     * 
     * @type {Array<IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner>}
     * @memberof TimeseriesDataJsonResponse
     */
    data: Array<IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInner>;
    /**
     * 
     * @type {IPagination}
     * @memberof TimeseriesDataJsonResponse
     */
    pagination: IPagination;
}

/**
 * Check if a given object implements the TimeseriesDataJsonResponse interface.
 */
export function instanceOfTimeseriesDataJsonResponse(value: object): value is TimeseriesDataJsonResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function TimeseriesDataJsonResponseFromJSON(json: any): TimeseriesDataJsonResponse {
    return TimeseriesDataJsonResponseFromJSONTyped(json, false);
}

export function TimeseriesDataJsonResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesDataJsonResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerFromJSON)),
        'pagination': IPaginationFromJSON(json['pagination']),
    };
}

  export function TimeseriesDataJsonResponseToJSON(json: any): TimeseriesDataJsonResponse {
      return TimeseriesDataJsonResponseToJSONTyped(json, false);
  }

  export function TimeseriesDataJsonResponseToJSONTyped(value?: TimeseriesDataJsonResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(IWithPaginationTimeseriesDataOrTimeseriesDataOneRowPerTimePeriodDataInnerToJSON)),
        'pagination': IPaginationToJSON(value['pagination']),
    };
}

