/* tslint:disable */
/* eslint-disable */
/**
 * avoindata-api
 * API for Fingrid Open Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPagination } from './IPagination';
import {
    IPaginationFromJSON,
    IPaginationFromJSONTyped,
    IPaginationToJSON,
    IPaginationToJSONTyped,
} from './IPagination';

/**
 * 
 * @export
 * @interface TimeseriesDataCsvResponse
 */
export interface TimeseriesDataCsvResponse {
    /**
     * 
     * @type {IPagination}
     * @memberof TimeseriesDataCsvResponse
     */
    pagination: IPagination;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesDataCsvResponse
     */
    data: string;
}

/**
 * Check if a given object implements the TimeseriesDataCsvResponse interface.
 */
export function instanceOfTimeseriesDataCsvResponse(value: object): value is TimeseriesDataCsvResponse {
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TimeseriesDataCsvResponseFromJSON(json: any): TimeseriesDataCsvResponse {
    return TimeseriesDataCsvResponseFromJSONTyped(json, false);
}

export function TimeseriesDataCsvResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesDataCsvResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': IPaginationFromJSON(json['pagination']),
        'data': json['data'],
    };
}

  export function TimeseriesDataCsvResponseToJSON(json: any): TimeseriesDataCsvResponse {
      return TimeseriesDataCsvResponseToJSONTyped(json, false);
  }

  export function TimeseriesDataCsvResponseToJSONTyped(value?: TimeseriesDataCsvResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': IPaginationToJSON(value['pagination']),
        'data': value['data'],
    };
}

